#!/usr/bin/env python3
"""
bundle.py — Binga Geoportal Layer Bundler
==========================================
Reads every .geojson file from assets/layers/ and writes
js/layers-data.js so the portal works on file:// without a server.

Usage (run from the Geoportal folder):
  python bundle.py

Run this whenever you edit a layer in QGIS.
"""

import json, os, sys
from pathlib import Path

# ── Paths (relative to this script) ──────────────────
ROOT        = Path(__file__).parent
LAYERS_DIR  = ROOT / 'assets' / 'layers'
OUTPUT_FILE = ROOT / 'js' / 'layers-data.js'

# ── Expected layer keys (must match LAYER_DEFS in config.js) ──
LAYER_KEYS = [
    'districtBoundary', 'wardBoundaries',   'villages',
    'roads',            'clinics',           'hospitals',
    'schools',          'touristSites',      'businessCentres',
    'serviceCentres',   'rivers',            'dams',
    'waterPoints',      'nationalParks',     'conservancies',
    'policeStations',   'policeBases',       'borderPosts',
    'airstrips',        'miningClaims',      'fishingCamps',
    'hotSprings',
]

def bundle():
    if not LAYERS_DIR.exists():
        print(f"ERROR: Layers folder not found: {LAYERS_DIR}")
        sys.exit(1)

    data    = {}
    loaded  = []
    missing = []

    for key in LAYER_KEYS:
        geojson_path = LAYERS_DIR / f'{key}.geojson'
        if geojson_path.exists():
            with open(geojson_path, encoding='utf-8') as f:
                data[key] = json.load(f)
            count = len(data[key].get('features', []))
            loaded.append(key)
            print(f'  ✓  {key:<22} {count} feature{"s" if count != 1 else ""}')
        else:
            missing.append(key)
            print(f'  ✗  {key:<22} (file not found — skipped)')

    if not loaded:
        print('\nERROR: No .geojson files found in', LAYERS_DIR)
        sys.exit(1)

    # ── Write output ──────────────────────────────────
    js = (
        '/* ═══════════════════════════════════════════════════\n'
        '   layers-data.js — Auto-generated by bundle.py\n'
        '   Binga Geoportal\n'
        '\n'
        '   DO NOT EDIT THIS FILE MANUALLY.\n'
        '   Edit the .geojson files in assets/layers/ using QGIS,\n'
        '   then re-run:  python bundle.py\n'
        '   ═══════════════════════════════════════════════════ */\n'
        '\n'
        'var sampleData = '
        + json.dumps(data, indent=2, ensure_ascii=False)
        + ';\n'
    )

    OUTPUT_FILE.parent.mkdir(parents=True, exist_ok=True)
    with open(OUTPUT_FILE, 'w', encoding='utf-8') as f:
        f.write(js)

    total = sum(len(v.get('features',[])) for v in data.values())
    size  = OUTPUT_FILE.stat().st_size // 1024

    print(f'\n  Bundled {len(loaded)}/{len(LAYER_KEYS)} layers')
    print(f'  Total features : {total}')
    print(f'  Output         : {OUTPUT_FILE}  ({size} KB)')
    if missing:
        print(f'  Missing files  : {", ".join(missing)}')
    print('\n  Done! Reload index.html in your browser.\n')

if __name__ == '__main__':
    print(f'\nBinga Geoportal — bundling layers from:\n  {LAYERS_DIR}\n')
    bundle()
